#ifndef TINY_SRV_DEF_H
#define TINY_SRV_DEF_H

/// protocol
#define TINY_SRV_VERSION = 0x59
#define TINY_SRV_MSG_HEAD_LEN (sizeof(int) + sizeof(char))
#define TINY_SRV_CMDINFO_OFFSET sizeof(int)
#define CMD_OFF_SET 12
#define CID_OFF_SET (33 + 32)
#define CID_OFFSET_TRACKER (18 + 32)

/// thread
#define TINY_SRV_ONTIME_SYN_ENTITY_TYPE 0x10
#define TINY_SRV_TIMEOUT_CHECK_ENTITY_TYPE 0x11
#define TINY_SRV_UDP_RECV_ENTITY_TYPE 0x12
#define TINY_SRV_UDP_PROC_SND_ENTITY_TYPE 0x13

/// cmd
#define TINY_SRV_BASE_CMD 0x22
#define TINY_SRV_ISRC_ONLINE 0x23
#define TINY_SRV_ISRC_ONLINE_RES 0x24
#define TINY_SRV_REPORT_RCLIST 0x25
#define TINY_SRV_REPORT_RCLIST_RES 0x26
#define TINY_SRV_INSERT_RC 0x27
#define TINY_SRV_INSERT_RC_RES 0x28
#define TINY_SRV_QUERY_PEER 0x29
#define TINY_SRV_QUERY_PEER_RES 0x30
#define TINY_SRV_DELETE_RCLIST 0x31
#define TINY_SRV_DELETE_RCLIST_RES 0x32
#define TINY_SRV_QUERY_PEERNUM 0x33
#define TINY_SRV_QUERY_PEERNUM_RES 0x34
#define TINY_SRV_DELETE_RCLISTNEW 0x35
#define TINY_SRV_DELETE_RCLISTNEW_RES 0x36

#endif
